//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Presentation.Validation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Presentation.Validation.ValidatorMessages", typeof(ValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле не установлено.
        /// </summary>
        public static string FieldIsNotSet {
            get {
                return ResourceManager.GetString("FieldIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инициалы не верны.
        /// </summary>
        public static string InvalidInitials {
            get {
                return ResourceManager.GetString("InvalidInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле слишком длинное.
        /// </summary>
        public static string LongField {
            get {
                return ResourceManager.GetString("LongField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно содержать только английские буквы.
        /// </summary>
        public static string MustContainOnlyEnglish {
            get {
                return ResourceManager.GetString("MustContainOnlyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно содержать только буквы.
        /// </summary>
        public static string MustContainOnlyLetters {
            get {
                return ResourceManager.GetString("MustContainOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле должно начинаться с заглавной буквы и содержать только буквы.
        /// </summary>
        public static string MustStartWithUpperAndContainsOnlyLetter {
            get {
                return ResourceManager.GetString("MustStartWithUpperAndContainsOnlyLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Средний пароль.
        /// </summary>
        public static string NormalPassword {
            get {
                return ResourceManager.GetString("NormalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1234567890.
        /// </summary>
        public static string passwordDigits {
            get {
                return ResourceManager.GetString("passwordDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        public static string passwordLowerChars {
            get {
                return ResourceManager.GetString("passwordLowerChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to !@#$%^&amp;*();&gt;&lt;?{}/*-+:.
        /// </summary>
        public static string passwordSpecialChars {
            get {
                return ResourceManager.GetString("passwordSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ABCDEFGHIJKLMNOPQRSTUVWXYZ.
        /// </summary>
        public static string passwordUpperChars {
            get {
                return ResourceManager.GetString("passwordUpperChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Хороший пароль.
        /// </summary>
        public static string StrongPassword {
            get {
                return ResourceManager.GetString("StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недопустимые символы.
        /// </summary>
        public static string UnallowedSymbols {
            get {
                return ResourceManager.GetString("UnallowedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данный логин уже используется другим пользователем.
        /// </summary>
        public static string UnuniqueLogin {
            get {
                return ResourceManager.GetString("UnuniqueLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слабый пароль.
        /// </summary>
        public static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
    }
}
