//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorMessages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Data.ValidatorMessages", typeof(ValidatorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле не установлено.
        /// </summary>
        internal static string FieldIsNotSet {
            get {
                return ResourceManager.GetString("FieldIsNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициалы не верны.
        /// </summary>
        internal static string InvalidInitials {
            get {
                return ResourceManager.GetString("InvalidInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле слишком длинное.
        /// </summary>
        internal static string LongField {
            get {
                return ResourceManager.GetString("LongField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно содержать только английские буквы.
        /// </summary>
        internal static string MustContainOnlyEnglish {
            get {
                return ResourceManager.GetString("MustContainOnlyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно содержать только буквы.
        /// </summary>
        internal static string MustContainOnlyLetters {
            get {
                return ResourceManager.GetString("MustContainOnlyLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле должно начинаться с заглавной буквы и содержать только буквы.
        /// </summary>
        internal static string MustStartWithUpperAndContainsOnlyLetter {
            get {
                return ResourceManager.GetString("MustStartWithUpperAndContainsOnlyLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Средний пароль.
        /// </summary>
        internal static string NormalPassword {
            get {
                return ResourceManager.GetString("NormalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1234567890.
        /// </summary>
        internal static string passwordDigits {
            get {
                return ResourceManager.GetString("passwordDigits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на abcdefghijklmnopqrstuvwxyz.
        /// </summary>
        internal static string passwordLowerChars {
            get {
                return ResourceManager.GetString("passwordLowerChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на !@#$%^&amp;*();&gt;&lt;?{}/*-+:.
        /// </summary>
        internal static string passwordSpecialChars {
            get {
                return ResourceManager.GetString("passwordSpecialChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ABCDEFGHIJKLMNOPQRSTUVWXYZ.
        /// </summary>
        internal static string passwordUpperChars {
            get {
                return ResourceManager.GetString("passwordUpperChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хороший пароль.
        /// </summary>
        internal static string StrongPassword {
            get {
                return ResourceManager.GetString("StrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Недопустимые символы.
        /// </summary>
        internal static string UnallowedSymbols {
            get {
                return ResourceManager.GetString("UnallowedSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данный логин уже используется другим пользователем.
        /// </summary>
        internal static string UnuniqueLogin {
            get {
                return ResourceManager.GetString("UnuniqueLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слабый пароль.
        /// </summary>
        internal static string WeakPassword {
            get {
                return ResourceManager.GetString("WeakPassword", resourceCulture);
            }
        }
    }
}
